import { Project } from './projects';

export const projectsFr: Project[] = [
    {
        id: 'isitopen',
        title: 'Is It Open?',
        subtitle: 'Vérificateur d\'état des magasins en temps réel avec effets d\'éclairage en ray-tracing.',
        icon: '/img/isitopen/isitopen_icon.png',
        image: '/img/isitopen/isitopen_preview.png',
        modalImage: '/img/isitopen/isitopen_check.png',
        technologies: ['Next.js 15', 'Tailwind CSS', 'Framer Motion', 'Google Maps API'],
        demoUrl: 'https://isitopen.romainbouchez.fr',
        description: 'Un vérificateur interactif en temps réel utilisant l\'API Google Places. Il dispose d\'une interface unique de style "Lampe" en ray-tracing qui signale visuellement l\'état du magasin (Ouvert/Fermé) grâce à des effets d\'éclairage dynamiques et du glassmorphisme.',
        features: [
            { icon: '🕒', title: 'État en Temps Réel', description: 'Vérifie instantanément les heures d\'ouverture selon l\'heure et le jour actuels.' },
            { icon: '💡', title: 'Interface Ray-Traced', description: 'Effets d\'éclairage dynamiques (Cyan/Vert/Rouge) reflétant l\'état du commerce.' },
            { icon: '🔍', title: 'Recherche Intelligente', description: 'Saisie semi-automatique Google Places intégrée pour trouver facilement un établissement.' },
            { icon: '📱', title: 'Mobile First', description: 'Mise en page réactive avec commandes et animations optimisées pour le tactile.' },
        ],
        email: 'bouchez@et.esiea.fr',
    },
    {
        id: 'ghost-note',
        title: 'Ghost Note',
        subtitle: 'Application de partage de notes éphémères à lecture unique, sans connaissance (Zero-Knowledge).',
        icon: '/img/ghost_note/ghost_note_icon.png',
        image: '/img/ghost_note/ghost_note_preview.png',
        modalTheme: 'dark',
        technologies: ['Next.js', 'Tailwind CSS', 'CryptoJS', 'Node.js', 'NeonDB'],
        demoUrl: 'https://ghostnote.romainbouchez.fr',
        description: 'Une application sécurisée où les données sont chiffrées dans le navigateur avant d\'atteindre le serveur. Garantit la confidentialité via une politique de lecture unique et l\'autodestruction immédiate du contenu déchiffré.',
        features: [
            { icon: '🔒', title: 'Chiffrement Côté Client', description: 'Chiffrement AES-256 dans le navigateur ; la clé n\'est jamais envoyée au serveur.' },
            { icon: '🚫', title: 'Confidentialité à Lecture Unique', description: 'Les données sont définitivement supprimées de la base de données après récupération.' },
            { icon: '🙈', title: 'Zero-Knowledge', description: 'Le serveur ne peut pas lire les notes ; seul le destinataire ayant la clé peut déchiffrer.' },
            { icon: '⏱️', title: 'Auto-Destruction', description: 'Les notes non lues expirent et sont supprimées après 24 heures.' },
        ],
        email: 'bouchez@et.esiea.fr',
    },
    {
        id: 'discord-chat',
        title: 'Harmony Chat',
        subtitle: 'Architecture de messagerie haute performance propulsée par Spring Boot & WebSockets.',
        icon: '/icon/discord_icon.png',
        image: '/img/projet_1_acceuil.png',
        technologies: ['Java Spring Boot', 'WebSockets', 'Maven', 'Thymeleaf', 'MySQL'],
        description: 'Une plateforme robuste à faible latence conçue pour répliquer les fonctionnalités clés de Discord. Basée sur un backend Spring Boot, elle utilise des connexions WebSocket persistantes pour une communication bidirectionnelle instantanée, supportant des salons publics simultanés et des messages privés sécurisés.',
        features: [
            { icon: '⚡', title: 'Architecture WebSocket', description: 'Canaux de communication full-duplex assurant une latence <50ms.' },
            { icon: '🔒', title: 'Sessions Privées', description: 'Salons de messagerie 1v1 sécurisés et éphémères avec isolation des sessions.' },
            { icon: '🛡️', title: 'Sécurité & Authentification', description: 'Flux d\'authentification personnalisé avec mots de passe hachés et gestion de session.' },
            { icon: '👥', title: 'Présence en Direct', description: 'Suivi de l\'état des utilisateurs en temps réel synchronisé entre clients.' },
        ],
        githubUrl: 'https://github.com/N3tup/Challenge-technique-JAVA-2024',
        email: 'bouchez@et.esiea.fr',
    },
    {
        id: 'restaurant',
        title: 'Fresh Foods',
        subtitle: 'Expérience culinaire numérique immersive avec animations GSAP fluides.',
        icon: '/img/Restaurant/Icon_Restaurant.png',
        image: '/img/Restaurant/Restaurant-home.png',
        technologies: ['GSAP Animation', 'Modern CSS', 'JavaScript', 'Responsive Design'],
        description: 'Une interface de restaurant visuellement saisissante conçue pour maximiser l\'engagement utilisateur. Crée une expérience de navigation cinématographique qui met en valeur l\'artisanat culinaire grâce à des séquences d\'apparition déclenchées par le défilement et morphing d\'éléments.',
        features: [
            { icon: '✨', title: 'Chorégraphie GSAP', description: 'Séquences de révélation complexes au défilement et morphing d\'éléments.' },
            { icon: '🎨', title: 'Hiérarchie Visuelle', description: 'Mise en page stratégique guidant l\'attention vers les plats à forte valeur.' },
            { icon: '📅', title: 'Moteur de Réservation', description: 'Logique de validation personnalisée pour une gestion fluide des tables.' },
            { icon: '📱', title: 'Interface Adaptative', description: 'Réactivité fluide assurant la cohérence de la marque sur tous les écrans.' },
        ],
        demoUrl: '/RESTAURANT/index.html',
        email: 'bouchez@et.esiea.fr',
    },
    {
        id: 'rdv-php',
        title: 'SystemeRDV',
        subtitle: 'Plateforme complète de planification pour la gestion des réservations et des profils.',
        icon: '/img/Form_logo.png',
        image: '/img/RDV-1.png',
        technologies: ['PHP 8', 'MySQL', 'PDO', 'Auth Security'],
        description: 'Solution full-stack de gestion des rendez-vous axée sur l\'intégrité des données et l\'optimisation des workflows. Gère les contraintes complexes, la définition des rôles utilisateurs et le suivi des disponibilités via une base de données relationnelle normalisée.',
        features: [
            { icon: '📅', title: 'Gestion des Créneaux', description: 'Algorithme de détection des conflits empêchant les doubles réservations.' },
            { icon: '👤', title: 'Rôles Utilisateurs', description: 'Système de permissions granulaire séparant les capacités clients et administrateurs.' },
            { icon: '💾', title: 'Persistance des Données', description: 'Couche d\'abstraction PDO pour des transactions SQL sécurisées et efficaces.' },
            { icon: '🔐', title: 'Contrôle de Session', description: 'Mécanismes de connexion robustes protégeant les données du profil.' },
        ],
        demoUrl: '/php/index.php',
        email: 'bouchez@et.esiea.fr',
    },
    {
        id: 'fast-typing',
        title: 'Fast-Typing',
        subtitle: 'Outil analytique de frappe compétitive conçu pour améliorer la vitesse et la précision.',
        icon: '/img/Fast-Typing/Icon_Fast_Typing.png',
        image: '/img/Fast-Typing/Fast-typing-menu.png',
        technologies: ['Vanilla JS', 'Async/Await', 'MySQL', 'Statistical Analysis'],
        description: 'Une application interactive de suivi des performances qui gamifie la maîtrise de la frappe au clavier. Elle capture les micro-interactions pour générer des rapports statistiques détaillés sur les mots par minute (WPM) et la précision, favorisant l\'amélioration continue grâce aux données.',
        features: [
            { icon: '⚡', title: 'Métrique en Temps Réel', description: 'Calcul en direct des WPM et de la précision au clavier avec zéro délai.' },
            { icon: '🌍', title: 'Moteur Bilingue', description: 'Génération dynamique de corpus supportant les dictionnaires français et anglais.' },
            { icon: '📊', title: 'Visualisation des Données', description: 'Graphiques de performances historiques pour visualiser la courbe d\'apprentissage.' },
            { icon: '🏆', title: 'Système de Classement', description: 'Infrastructure de classement mondial favorisant l\'engagement compétitif des utilisateurs.' },
        ],
        demoUrl: 'https://fast-typing.romainbouchez.fr',
        email: 'bouchez@et.esiea.fr',
    },
    {
        id: 'twitthe',
        title: 'Twitthé',
        subtitle: 'Réseau social de nouvelle génération conçu pour l\'évolutivité et l\'interaction en temps réel.',
        icon: '/img/Twitthe/Icon_twitthe.png',
        image: '/img/Twitthe/Twitthe-home.png',
        technologies: ['Next.js 15', 'Prisma ORM', 'Deep Learning', 'PostgreSQL', 'Clerk Auth'],
        description: 'Un écosystème de médias sociaux moderne conçu avec les principes de la stack T3. Comprend un backend relationnel performant, des mises à jour UI optimistes pour un retour instantané, et un environnement entièrement typé garantissant la fiabilité en production.',
        features: [
            { icon: '🔄', title: 'UI Optimiste', description: 'Mises à jour immédiates de l\'état avant la confirmation du serveur.' },
            { icon: '🔔', title: 'Système d\'Événements', description: 'Logique complexe de répartition des notifications pour les activités du graphe social.' },
            { icon: '🛡️', title: 'Sécurité du Typage', description: 'Validation de bout en bout, du schéma de base de données aux composants clients.' },
            { icon: '🎨', title: 'Thématisation Moderne', description: 'Mode sombre/clair sensible au contexte avec Tailwind CSS.' },
        ],
        githubUrl: 'https://github.com/RomainBouchez/Twitthe.git',
        email: 'bouchez@et.esiea.fr',
    },
    {
        id: 'aical',
        title: 'AICal',
        subtitle: 'Assistant nutritionnel par vision par ordinateur propulsé par l\'IA multimodale Gemini.',
        icon: '/img/AiCal/icon_AICal.png',
        image: '/img/AiCal/aical-mainpage.jpg',
        modalTheme: 'dark',
        technologies: ['Gemini Vision Pro', 'Next.js 15', 'Computer Vision', 'Data Vis'],
        description: 'Une application de santé avant-gardiste reliant la vision par ordinateur et la science de la nutrition. En exploitant des LLMs multimodaux, elle transforme les images brutes d\'aliments en données macronutritionnelles structurées, permettant un suivi et une analyse faciles.',
        features: [
            { icon: '👁️', title: 'Analyse Visuelle par l\'IA', description: 'Reconnaissance alimentaire Zero-Shot et estimation volumétrique via Gemini Pro.' },
            { icon: '📊', title: 'Agrégation des Nutriments', description: 'Pipelines de transformation de données complexes pour le calcul macro quotidien.' },
            { icon: '🎯', title: 'Suivi des Objectifs', description: 'Visualisation dynamique de la progression par rapport aux objectifs physiologiques personnalisés.' },
            { icon: '📅', title: 'Indexation Historique', description: 'Interrogation temporelle efficace des journaux nutritionnels passés.' },
        ],
        demoUrl: 'https://aical.romainbouchez.fr/',
        githubUrl: 'https://github.com/RomainBouchez/CalAi/',
        email: 'bouchez@et.esiea.fr',
    },
    {
        id: 'ov-amsterdam',
        title: 'OV-AMS Analysis',
        subtitle: 'Analyse géospatiale Big Data optimisant le réseau de transport d\'Amsterdam.',
        icon: '/img/OV/Icon_OV.png',
        image: '/img/OV/ov-amsterdam-map.png',
        technologies: ['Python Pandas', 'Folium GIS', 'Data Science', 'Statistical Modeling'],
        description: 'Initiative de data science menée à la HVA d\'Amsterdam, utilisant des datasets massifs pour optimiser les modèles tarifaires des transports publics. Le projet applique le clustering géospatial et l\'analyse de séries temporelles pour identifier les inefficacités.',
        features: [
            { icon: '🗺️', title: 'Cartographie Géospatiale', description: 'Génération de cartes thermiques interactives visualisant les trafics denses.' },
            { icon: '📈', title: 'Reconnaissance de Modèles', description: 'Identification des comportements temporels des navetteurs via l\'analyse statistique.' },
            { icon: '💶', title: 'Optimisation des Coûts', description: 'Remodelage algorithmique des tarifs pour avantager les étudiants.' },
            { icon: '🐍', title: 'Pipelines Pandas', description: 'Processus ETL à haut volume nettoyant et structurant les logs de transport bruts.' },
        ],
        email: 'bouchez@et.esiea.fr',
    },
    {
        id: 'chess-robot',
        title: 'AutoChess Bot',
        subtitle: 'Système mécatronique autonome intégrant l\'IA Stockfish avec une action physique.',
        icon: '/img/PST4A/icon_PST4A.png',
        image: '/img/PST4A/chess-robot-preview.png',
        technologies: ['Robotics', 'Python', 'Arduino', 'Stockfish Engine', '3D Printing'],
        description: 'Projet d\'ingénierie interdisciplinaire fusionnant la stratégie numérique avec la réalité physique. Un bras robotique à 3 axes sur mesure exécute les coups de Stockfish en temps réel, nécessitant une cartographie de coordonnées précise.',
        features: [
            { icon: '🤖', title: 'Cinématique Inverse', description: 'Logique de coordination motrice traduisant la grille A1-H8 pour cartographier les coups spatiaux.' },
            { icon: '♟️', title: 'Cerveau Stockfish', description: 'Intégration avec le moteur d\'échecs open-source le plus puissant au monde.' },
            { icon: '🖨️', title: 'Matériel Personnalisé', description: 'Fabrication de bout en bout des pièces mécaniques via CAO et impression 3D.' },
            { icon: '🎮', title: 'Interface Hybride', description: 'Synchronisation fluide entre l\'état physique du plateau et l\'UI numérique.' },
        ],
        email: 'bouchez@et.esiea.fr',
        status: 'In Progress',
    },
    {
        id: 'iads-project',
        title: 'Oncology AI Research',
        subtitle: 'Initiative Deep Learning pour l\'analyse prédictive du cancer du sein à l\'aide de données cliniques.',
        icon: '/img/IADS/icon_IADS.png',
        image: '/img/IADS/iads-main.svg',
        technologies: ['Deep Learning', 'PyTorch', 'Medical Imaging', 'Bioinformatics'],
        description: 'Un projet de recherche majeur pluriannuel axé sur l\'application des Réseaux de Neurones Convolutifs (CNN) aux données histologiques. Travail avec des datasets réels d\'hôpitaux pour augmenter la précision diagnostique grâce à la modélisation prédictive.',
        features: [
            { icon: '🧬', title: 'ETL Clinique', description: 'Traitement sécurisé et normalisation d\'ensembles de données médicaux sensibles.' },
            { icon: '🧠', title: 'Architecture du Modèle', description: 'Conception et entraînement de réseaux neuronaux spécialisés pour évaluer la malignité.' },
            { icon: '📊', title: 'Analyse Prédictive', description: 'Évaluation statistique de la précision/rappel des modèles en contexte clinique.' },
            { icon: '🔬', title: 'Méthodologie de Recherche', description: 'Approche scientifique rigoureuse pour la validation et le réglage des hyperparamètres.' },
        ],
        email: 'bouchez@et.esiea.fr',
        status: 'In Progress',
    },
    {
        id: 'wikilink-race',
        title: 'WikiLink Race',
        subtitle: 'Navigue de page en page sur Wikipedia le plus rapidement possible !',
        icon: '/img/wikilink-race/icon.png',
        image: '/img/wikilink-race/preview.png',
        modalImage: '/img/wikilink-race/game_page.png',
        technologies: ['React 19', 'TypeScript 5.8', 'Vite', 'Tailwind CSS', 'Firebase (Firestore/Auth)', 'Wikipedia REST API'],
        description: 'WikiLink Race est basé sur le concept des Six degrés de séparation appliqué à Wikipedia. Le jeu génère une page de départ et une page cible : l\'objectif est de naviguer de l\'une à l\'autre uniquement en cliquant sur les liens internes des articles Wikipedia. Le score dépend du temps écoulé et du nombre de clics (optimisation du chemin le plus court). Propose 3 modes de jeu pour varier l\'expérience.',
        features: [
            {
                icon: '🎮',
                title: '3 Modes de Jeu',
                description: `Une expérience variée conçue pour tous les types de joueurs :\n\n• Entraînement : Exercez-vous librement sur des cibles aléatoires.\n• Défi du jour : Un trajet unique renouvelé chaque nuit, identique pour tous. Comparez vos scores et maintenez votre "streak" !\n• Multijoueur : Créez des salons privés et affrontez vos amis en temps réel avec des règles configurables (manches, temps, difficulté).`
            },
            {
                icon: '🌐',
                title: 'Multijoueur Temps Réel "Serverless"',
                description: `Une architecture multijoueur synchrone innovante sans WebSockets dédiés, s'appuyant sur les listeners onSnapshot de Firestore.\n\nCette approche légère permet de visualiser instantanément la progression (clics, temps et page actuelle) de vos adversaires.\nRésultat : une latence quasi imperceptible (~100ms) pour une compétition très fluide.`
            },
            {
                icon: '🧠',
                title: 'Curator d\'Articles Algorithmique',
                description: `Pour garantir des parties équilibrées et écarter les cibles impossibles ("cul-de-sac" encyclopédique), le jeu s'appuie sur un algorithme de sélection hybride :\n\n• 80% d'articles populaires soigneusement modérés.\n• 20% d'articles totalement aléatoires issus de l'API /page/random/summary de Wikipedia.`
            },
            {
                icon: '📊',
                title: 'Ecosystème Joueur & Scoring',
                description: `Intégration Firebase complète permettant de jouer anonymement ou de synchroniser sa progression.\n\n• Scoring Stratégique : Pondère très fortement les clics (x10) par rapport au temps global pour récompenser l'optimisation intelligente du chemin Wikipedia.\n• Profil : Statistiques moyennes, friend codes et suivi méticuleux des séries quotidiennes (streaks).`
            },
        ],
        demoUrl: 'https://wikilink-race.romainbouchez.fr/',
        githubUrl: 'https://github.com/RomainBouchez/wikilink-race',
        email: 'bouchez@et.esiea.fr',
        new: true,
    },
];
